# Generated by Django 3.2.8 on 2021-11-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_produce_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='picture',
            field=models.FileField(blank=True, upload_to='produce_pics'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='is_organic',
            field=models.BooleanField(verbose_name='Organic'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='min_quantity',
            field=models.FloatField(verbose_name='Min. Qty'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='name',
            field=models.CharField(choices=[('CARROTS', 'Carrots'), ('KALE', 'Kale'), ('BROCCOLI', 'Broccoli'), ('PEAS', 'Peas'), ('SWEET POTATOES', 'Sweet potatoes'), ('BEETS', 'Beets'), ('SPINACH', 'Spinach'), ('TOMATOES', 'Tomatoes'), ('GARLIC', 'Garlic'), ('ONIONS', 'Onions')], max_length=20),
        ),
    ]
