# Generated by Django 3.2.9 on 2021-11-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_produce_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='is_organic',
            field=models.BooleanField(verbose_name='Organic'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='min_quantity',
            field=models.FloatField(verbose_name='Min. Quantity'),
        ),
    ]
