# Generated by Django 3.2.8 on 2021-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_produce_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='name',
            field=models.CharField(choices=[('CARROTS', 'Carrots'), ('KALE', 'Kale'), ('BROCCOLI', 'Broccoli'), ('PEAS', 'Peas'), ('SWEET POTATOES', 'Sweet potatoes'), ('BEETS', 'Beets'), ('SPINACH', 'Spinach'), ('TOMATOES', 'Tomatoes'), ('GARLIC', 'Garlic'), ('ONIONS', 'Onions')], max_length=20),
        ),
    ]
