# Generated by Django 3.2.8 on 2021-11-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0003_alter_produce_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='name',
            field=models.CharField(choices=[('Carrots', 'Carrots'), ('KALE', 'Kale'), ('BROCCOLI', 'Broccoli'), ('PEAS', 'Peas'), ('SWEET POTATOES', 'Sweet potatoes'), ('BEETS', 'Beets'), ('SPINACH', 'Spinach'), ('TOMATOES', 'Tomatoes'), ('GARLIC', 'Garlic'), ('ONIONS', 'Onions')], max_length=20),
        ),
    ]
