# Generated by Django 3.2.9 on 2021-11-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0003_auto_20211123_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='min_quantity',
            field=models.FloatField(verbose_name='Min. Qty'),
        ),
    ]
