# Generated by Django 3.2.9 on 2021-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0004_alter_produce_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='picture',
            field=models.ImageField(blank=True, upload_to='produce_pics'),
        ),
    ]
