# Generated by Django 3.2.9 on 2021-11-27 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0005_alter_produce_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='min_quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Min. Qty'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
