# Generated by Django 3.2.9 on 2021-11-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0005_alter_produce_name'),
        ('produce', '0006_alter_produce_picture'),
    ]

    operations = [
    ]
