# Generated by Django 3.1.5 on 2021-12-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0006_auto_20211126_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='mode_of_sale',
            field=models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail'), ('PICK YOUR OWN', 'Pick Your Own')], default='WHOLESALE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produce',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
