# Generated by Django 3.2.9 on 2021-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0007_auto_20211203_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
