# Generated by Django 3.2.9 on 2021-12-03 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0008_alter_produce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
