# Generated by Django 3.2.9 on 2021-12-03 23:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_alter_farm_name'),
        ('produce', '0009_alter_produce_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farm', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price ($)'),
        ),
    ]
