# Generated by Django 3.2.9 on 2021-12-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0010_auto_20211203_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='purchase_units',
            field=models.CharField(choices=[('OUNCE', 'Oz'), ('PINT', 'pt'), ('QUART', 'qt'), ('BUNCH', 'Bunch'), ('POUND', 'lbs')], default='POUND', max_length=50),
            preserve_default=False,
        ),
    ]
