# Generated by Django 3.2.9 on 2021-11-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20211107_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
