# Generated by Django 3.2.9 on 2021-11-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_farm_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
