# Generated by Django 3.2.9 on 2021-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20211109_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone'),
        ),
    ]
