# Generated by Django 3.2.8 on 2021-11-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20211123_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
