# Generated by Django 3.2.9 on 2021-12-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_farm_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
